name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: macos-latest
          #   TARGET: macos
          #   CMD_BUILD: >
          #       pyinstaller -F -w -n Sandy src/main.py &&
          #       cd dist/ &&
          #       zip -r9 clipster clipster.app/                
          #   OUT_FILE_NAME: clipster.zip
          #   ASSET_MIME: application/zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: PyInstaller -F -w -n Sandy src/main.py
            OUT_FILE_NAME: Sandy.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt        
    - name: Build with pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}
